### ISSUE TITLE
unit mapping

### ISSUE THREAD

**Issue by jakobsarthur** [BONSAMURAIS/Correspondence-tables#13]
should include unit conversions (e.g. kWh to Joules etc)
Depending on what units entso comes in. Exiobase comes in TJ.

**Comment by mfastudillo** [comment]
we will need a correspondence between units used in exiobase to (which are very few) to something [here ](http://www.ontology-of-units-of-measure.org/resource/om-2/terajoule)

e.g. Terajoule : http://www.ontology-of-units-of-measure.org/resource/om-2/terajoule

**Comment by tgmorais** [comment]
The file is [here](https://github.com/BONSAMURAIS/Correspondence-tables/blob/master/final_tables/Unit_exiobase_bentso_converter.csv).
