### ISSUE TITLE
Move all CSVs to `raw` (or similar) directory

### ISSUE THREAD

**Issue by cmutel** [BONSAMURAIS/Correspondence-tables#2]
Should have separate directories for raw data, output data, and processing scripts

**Comment by mfastudillo** [comment]
I moved all the tables to a "raw" folder.

(ps: I am not fully aware of _good manners_ managing issues, am I supossed to close it or is it the person who raised the issue supposed to do it ?

**Comment by cmutel** [comment]
@mfastudillo It is fine to close an issue yourself if you fixed the problem. The issue creator will get an email, and can re-open it if they need to.

For now, and during the hackathon, communicating bilaterally is fine. However, afterwards we would like to use the [pull request workflow](https://guides.github.com/introduction/flow/) as much as possible, to help manage changes better, especially to the core repositories. This isn't a comment for you, but rather for everyone. When many people collaborate, it is easy to miss what is happening, and pull requests are a nice encapsulation of major changes.
