### ISSUE TITLE
missing skeleton

### ISSUE THREAD

**Issue by mfastudillo** [BONSAMURAIS/Correspondence-tables#25]
This repo was done before the start of the hackathon, and some of the basic stuff is missing. Together with @massimopizzol we copied and adapted files from arborist to try to solve this. Currently as a [separate branch](https://github.com/BONSAMURAIS/Correspondence-tables/tree/repr_skeleton).

**Comment by mfastudillo** [comment]
this repo was created before the Barcelona hackathon and name does not follow conventions. it should be underscore and `_` instead of `-` .

I think the name needs to be changed, otherwise when I try to import the module it gives an error. Opinions of more versed people are welcomed :) @kuzeko ? @tngTUDOR

**Comment by kuzeko** [comment]
I think you can change the repository name and then you have to clone it back to your laptop

**Comment by mfastudillo** [comment]
Solved. Now the basic functionalities of skeleton are there. 
https://github.com/BONSAMURAIS/correspondence_tables/pull/26
