### ISSUE TITLE
exiobaser 3.3.17 labels

### ISSUE THREAD

**Issue by mfastudillo** [BONSAMURAIS/Correspondence-tables#27]
Exiobase has some strange labels for products and activities like: `Retail  trade services[...]` (double space between words) or inconsistent use of words e.g. `Animal products nec` and `Membership organisation services n.e.c. (91)`. Should we apply some consistency rules on the activity and flow object labels ?

**Comment by boweidema** [comment]
In my opinion, it would be best practice to accept such "spelling errors" etc. in the original classification, in order not to invent a "BONSAI interpretation of the EXIOBASE classification" that we then would have the responsibility to maintain. The only time we should correct such errors is if they would introduce "illegal" conflicts (e.g. two different classes with the same name)

**Comment by cmutel** [comment]
I reluctantly agree. Best practice in this case would be to communicate with the EXIOBASE team, to get them to make consistent and correct labels in the next release (we don't want to have to create custom mappings each time they make a release).
