### ISSUE TITLE
LC-IMPACT IPCC to US EPA elementary flows

### ISSUE THREAD

**Issue by mfastudillo** [BONSAMURAIS/Correspondence-tables#7]
- [x] create the correspondence table US EPA to IPCC CF
- [x] document metadata
- [x] upload table with CF

**Comment by tgmorais** [comment]
I uploaded the file in the “raw” folder.
I also added the metadata in the file “_Overview_of_available_correspondence_files.csv”

**Comment by mfastudillo** [comment]
Nice, when @tgmorais1 did the correspondence between LC-Impact (which exactly match IPCC names) and US EPA there are some substances missing. We will write to the EPA people to try to understand why.

the file with the name correspondence is [here](https://github.com/BONSAMURAIS/Correspondence-tables/blob/master/raw/lcimpact_to_US_EPA_names.csv ).

**Comment by mfastudillo** [comment]
@tgmorais1 does IPCC license the results in a specific way? we need to figure out if we can actually include them in bonsai.

**Comment by tgmorais** [comment]
I think that IPCC results are not licensed, but I will look for it.

**Comment by tgmorais** [comment]
I looked in to the IPCC report and I could not find anything related with licensing of the results.

**Comment by mfastudillo** [comment]
the final version (for the moment) is in the folder for final tables, although metadata is missing.
